spring:
  application:
    name: "DakarHelperService"

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mongodb:
    uri: ${MONGODB_URI}

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO